'use client'
import { useState } from 'react'
import { useRouter } from 'next/navigation'

interface ShareBarProps {
  symbol: string
  verdict: string
  price: string
  change24h: number
  tokenId: string
}

export default function ShareBar({ symbol, verdict, price, change24h, tokenId }: ShareBarProps) {
  const router = useRouter()
  const [copied, setCopied] = useState(false)

  const pageUrl = typeof window !== 'undefined' ? window.location.href : `https://synthterminal.app/report/${tokenId}`

  function shareOnX() {
    const text = `$${symbol} Intelligence Report\n${verdict} · ${price} · ${change24h >= 0 ? '+' : ''}${change24h.toFixed(2)}%\n\nGenerated by @SynthVirtual · AI analytics for Base\n\n${pageUrl}`
    window.open(`https://twitter.com/intent/tweet?text=${encodeURIComponent(text)}`, '_blank', 'width=600,height=400')
  }

  async function copyLink() {
    try {
      await navigator.clipboard.writeText(pageUrl)
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    } catch {
      // fallback
    }
  }

  function openInSynth() {
    router.push(`/synth?token=${symbol}`)
  }

  const BTN: React.CSSProperties = {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    padding: '10px 18px',
    background: 'transparent',
    border: '1px solid rgba(0,255,65,0.3)',
    color: 'rgba(0,255,65,0.8)',
    fontFamily: 'var(--font-mono)',
    fontSize: '11px',
    letterSpacing: '0.15em',
    cursor: 'pointer',
    textTransform: 'uppercase' as const,
    transition: 'all 0.2s',
    flexShrink: 0,
  }

  return (
    <div style={{
      position: 'sticky',
      bottom: 0,
      left: 0,
      right: 0,
      zIndex: 10,
      background: 'rgba(0,4,1,0.97)',
      borderTop: '1px solid rgba(0,255,65,0.2)',
      padding: '12px 16px',
      display: 'flex',
      gap: '8px',
      alignItems: 'center',
      backdropFilter: 'blur(12px)',
      justifyContent: 'center',
      flexWrap: 'wrap',
    }}>
      <button onClick={shareOnX} style={BTN}>
        ↗ SHARE ON X
      </button>
      <button onClick={copyLink} style={{ ...BTN, color: copied ? 'var(--green)' : 'rgba(0,255,65,0.8)', borderColor: copied ? 'rgba(0,255,65,0.6)' : 'rgba(0,255,65,0.3)' }}>
        {copied ? '✓ COPIED' : '📋 COPY LINK'}
      </button>
      <button onClick={openInSynth} style={BTN}>
        ◉ OPEN IN SYNTH
      </button>
    </div>
  )
}
